CREATE TABLE CUSTOMER( 
CUST_ID NUMBER(10) PRIMARY KEY NOT NULL, 
CUST_NAME VARCHAR2(25) NOT NULL, 
EMAIL_ID VARCHAR2(25) NOT NULL, 
CONTACT_NO INT, 
ADDRESS VARCHAR2(50), 
STATE VARCHAR2(15), 
CITY VARCHAR2(15), 
PINCODE VARCHAR2(10)  
);


CREATE TABLE ADMIN ( 
  ADMIN_ID NUMBER(10) PRIMARY KEY NOT NULL, 
  ADMIN_NAME VARCHAR2(25) NOT NULL 
);


CREATE TABLE ADMIN_ROLES ( 
ADMIN_ID NUMBER(10), 
CUST_ID NUMBER(10), 
CONSTRAINT ADMIN_ID_FK FOREIGN KEY (ADMIN_ID) REFERENCES 
ADMIN(ADMIN_ID), 
CONSTRAINT CUST_ID_FK FOREIGN KEY (CUST_ID) REFERENCES 
CUSTOMER(CUST_ID) 
);

CREATE TABLE ACCOUNT ( 
ACC_ID NUMBER(10) PRIMARY KEY NOT NULL, 
ACC_NO VARCHAR2(25) NOT NULL, 
CUST_ID NUMBER(10), 
CUST_NAME VARCHAR2(25), 
CONSTRAINT  CUSTOMER_ID_FK 
FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID) 
);

CREATE TABLE BILLING ( 
METER_ID NUMBER(10) PRIMARY KEY NOT NULL, 
ACC_ID NUMBER(10), 
CUST_ID NUMBER(10), 
PER_MONTH_UNITS NUMBER(6,2), 
AMOUNT_PER_UNIT NUMBER(6,2) DEFAULT 10, 
TOTAL_AMOUNT NUMBER(6,2), 
CONSTRAINT B_ACCOUNT_ID_FK 
FOREIGN KEY (ACC_ID) REFERENCES ACCOUNT(ACC_ID), 
CONSTRAINT B_CUSTOMER_ID_FK 
FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID) 
);

CREATE TABLE ELEC_BOARD( 
EBOARD_ID NUMBER(10) PRIMARY KEY NOT NULL, 
EBOARD_NAME VARCHAR2(50)); 


CREATE TABLE TARIFF( 
TARIFF_ID NUMBER(10) PRIMARY KEY NOT NULL , 
TARIFF_TYPE VARCHAR2(25)  
);

CREATE TABLE INVOICE ( 
INVOICE_ID NUMBER(10) PRIMARY KEY NOT NULL,  
EBOARD_ID NUMBER(10) NOT NULL, 
ACC_NO VARCHAR2(25), 
TARIFF_ID NUMBER(10), 
READING_DATE date, 
METER_ID NUMBER(10), 
CONSTRAINT E_BOARD_ID_FK 
FOREIGN KEY (EBOARD_ID) REFERENCES ELEC_BOARD(EBOARD_ID), 
CONSTRAINT TARIFF_ID_FK 
FOREIGN KEY (TARIFF_ID) REFERENCES TARIFF(TARIFF_ID), 
CONSTRAINT METER_ID_FK 
FOREIGN KEY (METER_ID) REFERENCES BILLING(METER_ID), 
CONSTRAINT READ_DATE_CHK CHECK (READING_DATE > date('01
01-2023', 'DD-MM-YYYY')) 
);

INSERT INTO CUSTOMER VALUES (1, 'Aditya Sharma', 'aditya.sharma@email.in', 9876543210, '101 Royal Enclave', 'Maharashtra', 'Mumbai', '400001');
INSERT INTO CUSTOMER VALUES (2, 'Neha Patel', 'neha.patel@email.in', 8765432109, '202 Green Meadows', 'Maharashtra', 'Pune', '411001');
INSERT INTO CUSTOMER VALUES (3, 'Sandeep Desai', 'sandeep.desai@email.in', 7654321098, '303 Silver Springs', 'Karnataka', 'Bangalore', '560001');
INSERT INTO CUSTOMER VALUES (4, 'Pooja Rao', 'pooja.rao@email.in', 6543210987, '404 Lotus Towers', 'Karnataka', 'Bangalore', '560001');
INSERT INTO CUSTOMER VALUES (5, 'Vikas Singh', 'vikas.singh@email.in', 5432109876, '505 Blossom Residency', 'Telangana', 'Hyderabad', '500001');
INSERT INTO CUSTOMER VALUES (6, 'Anjali Reddy', 'anjali.reddy@email.in', 4321098765, '606 Serene Haven', 'Telangana', 'Hyderabad', '500001');
INSERT INTO CUSTOMER VALUES (7, 'Rahul Verma', 'rahul.verma@email.in', 3210987654, '707 Majestic Heights', 'Maharashtra', 'Mumbai', '400706');
INSERT INTO CUSTOMER VALUES (8, 'Megha Kapoor', 'megha.kapoor@email.in', 2109876543, '808 Sapphire Towers', 'Gujarat', 'Ahmedabad', '380001');
INSERT INTO CUSTOMER VALUES (9, 'Sachin Yadav', 'sachin.yadav@email.in', 1098765432, '909 Golden Orchid', 'Gujarat', 'Ahmedabad', '380001');
INSERT INTO CUSTOMER VALUES (10, 'Sonia Joshi', 'sonia.joshi@email.in', 9876543210, '1001 Tranquil Residences', 'Maharashtra', 'Pune', '411014');

INSERT INTO ADMIN VALUES (101, 'Rahul Kumar');
INSERT INTO ADMIN VALUES (201, 'Sneha Verma');
INSERT INTO ADMIN VALUES (301, 'Amit Shah');
INSERT INTO ADMIN VALUES (401, 'Nisha Kapoor');
INSERT INTO ADMIN VALUES (501, 'Vijay Malhotra');

INSERT INTO ADMIN_ROLES VALUES (101, 1);
INSERT INTO ADMIN_ROLES VALUES (101, 6);
INSERT INTO ADMIN_ROLES VALUES (201, 2);
INSERT INTO ADMIN_ROLES VALUES (201, 7);
INSERT INTO ADMIN_ROLES VALUES (301, 3);
INSERT INTO ADMIN_ROLES VALUES (301, 8);
INSERT INTO ADMIN_ROLES VALUES (401, 4);
INSERT INTO ADMIN_ROLES VALUES (401, 9);
INSERT INTO ADMIN_ROLES VALUES (501, 5);
INSERT INTO ADMIN_ROLES VALUES (501, 10);

INSERT INTO ACCOUNT VALUES (11, '21001', 1, 'Aditya Sharma');
INSERT INTO ACCOUNT VALUES (22, '82002', 2, 'Neha Patel');
INSERT INTO ACCOUNT VALUES (33, '73003', 3, 'Sandeep Desai');
INSERT INTO ACCOUNT VALUES (44, '24004', 4, 'Pooja Rao');
INSERT INTO ACCOUNT VALUES (55, '55005', 5, 'Vikas Singh');
INSERT INTO ACCOUNT VALUES (66, '66006', 6, 'Anjali Reddy');
INSERT INTO ACCOUNT VALUES (77, '17007', 7, 'Rahul Verma');
INSERT INTO ACCOUNT VALUES (88, '48008', 8, 'Megha Kapoor');
INSERT INTO ACCOUNT VALUES (99, '19009', 9, 'Sachin Yadav');
INSERT INTO ACCOUNT VALUES (111, '210010', 10, 'Sonia Joshi');

INSERT INTO BILLING VALUES (1101, 11, 1, 150.5, 10, NULL);
INSERT INTO BILLING VALUES (1102, 22, 2, 200.75, 10, NULL);
INSERT INTO BILLING VALUES (1103, 33, 3, 120.25, 10, NULL);
INSERT INTO BILLING VALUES (1104, 44, 4, 180.0, 10, NULL);
INSERT INTO BILLING VALUES (1105, 55, 5, 250.5, 10, NULL);
INSERT INTO BILLING VALUES (1106, 66, 6, 300.0, 10, NULL);
INSERT INTO BILLING VALUES (1107, 77, 7, 170.75, 10, NULL);
INSERT INTO BILLING VALUES (1108, 88, 8, 190.5, 10, NULL);
INSERT INTO BILLING VALUES (1109, 99, 9, 220.25, 10, NULL);
INSERT INTO BILLING VALUES (1110, 111, 10, 280.0, 10, NULL);

INSERT INTO ELEC_BOARD VALUES (100, 'Maharashtra State Electricity Board');
INSERT INTO ELEC_BOARD VALUES (200, 'Karnataka Power Transmission Corporation');
INSERT INTO ELEC_BOARD VALUES (300, 'Telangana Power Distribution Company');
INSERT INTO ELEC_BOARD VALUES (400, 'Gujarat Energy Development Agency');

INSERT INTO TARIFF VALUES (1, 'Seasonal Tariff');
INSERT INTO TARIFF VALUES (2, 'Time-of-Use Tariff');
INSERT INTO TARIFF VALUES (3, 'Flat Rate Tariff');

INSERT INTO INVOICE (INVOICE_ID, EBOARD_ID, ACC_NO, TARIFF_ID, READING_DATE, METER_ID)
VALUES (1111, 100, '21001', 1, '2023-01-25', 1101);

INSERT INTO INVOICE (INVOICE_ID, EBOARD_ID, ACC_NO, TARIFF_ID, READING_DATE, METER_ID)
VALUES (2222, 100, '82002', 2, '2023-01-27', 1102);

INSERT INTO INVOICE (INVOICE_ID, EBOARD_ID, ACC_NO, TARIFF_ID, READING_DATE, METER_ID)
VALUES (3333, 200, '73003', 3, '2023-01-26', 1103);

INSERT INTO INVOICE (INVOICE_ID, EBOARD_ID, ACC_NO, TARIFF_ID, READING_DATE, METER_ID)
VALUES (4444, 200, '24004', 1, '2023-01-28', 1104);

INSERT INTO INVOICE (INVOICE_ID, EBOARD_ID, ACC_NO, TARIFF_ID, READING_DATE, METER_ID)
VALUES (5555, 300, '55005', 3, '2023-01-29', 1105);

INSERT INTO INVOICE (INVOICE_ID, EBOARD_ID, ACC_NO, TARIFF_ID, READING_DATE, METER_ID)
VALUES (6666, 300, '66006', 2, '2023-01-30', 1106);

INSERT INTO INVOICE (INVOICE_ID, EBOARD_ID, ACC_NO, TARIFF_ID, READING_DATE, METER_ID)
VALUES (7777, 100, '17007', 3, '2023-01-29', 1107);

INSERT INTO INVOICE (INVOICE_ID, EBOARD_ID, ACC_NO, TARIFF_ID, READING_DATE, METER_ID)
VALUES (8888, 400, '48008', 1, '2023-01-31', 1108);

INSERT INTO INVOICE (INVOICE_ID, EBOARD_ID, ACC_NO, TARIFF_ID, READING_DATE, METER_ID)
VALUES (9999, 400, '19009', 2, '2023-01-31', 1109);

INSERT INTO INVOICE (INVOICE_ID, EBOARD_ID, ACC_NO, TARIFF_ID, READING_DATE, METER_ID)
VALUES (1010, 100, '210010', 1, '2023-01-27', 1110);


UPDATE BILLING  
SET TOTAL_AMOUNT = PER_MONTH_UNITS * AMOUNT_PER_UNIT 
WHERE TOTAL_AMOUNT IS NULL;

ALTER TABLE INVOICE 
ADD CUST_ID NUMBER(10);

UPDATE INVOICE
SET CUST_ID = (
  SELECT CUST_ID
  FROM BILLING
  WHERE BILLING.METER_ID = INVOICE.METER_ID
)
WHERE CUST_ID IS NULL;
 
-- Update CUST_NAME from CUSTOMER
UPDATE INVOICE
SET CUST_NAME = (
    SELECT C.CUST_NAME
    FROM CUSTOMER C
    WHERE C.CUST_ID = INVOICE.CUST_ID
)
WHERE CUST_NAME IS NULL;

-- Update TOTAL_AMOUNT from BILLING
UPDATE INVOICE
SET TOTAL_AMOUNT = (
    SELECT B.TOTAL_AMOUNT
    FROM BILLING B
    WHERE B.METER_ID = INVOICE.METER_ID
)
WHERE TOTAL_AMOUNT IS NULL;

SELECT CUST_ID, CUST_NAME, INVOICE_ID, METER_ID, READING_DATE 
FROM INVOICE 
WHERE READING_DATE = '2023-01-27';

SELECT CUST_ID, CUST_NAME, ACC_ID, ACC_NO 
FROM ACCOUNT  
ORDER BY CUST_NAME ASC;

SELECT CUST_ID, CUST_NAME, READING_DATE, TOTAL_AMOUNT  
FROM INVOICE 
ORDER BY READING_DATE ASC;

SELECT * FROM BILLING WHERE PER_MONTH_UNITS > 200;
SELECT * FROM BILLING 
WHERE METER_ID % 2 <> 0;

SELECT CUST_ID, CUST_NAME, STATE, CITY, PINCODE 
FROM CUSTOMER 
WHERE STATE = 'Maharashtra';

SELECT C.CUST_ID, C.CUST_NAME, A.ADMIN_NAME 
FROM CUSTOMER C
JOIN ADMIN_ROLES AR ON C.CUST_ID = AR.CUST_ID
JOIN ADMIN A ON AR.ADMIN_ID = A.ADMIN_ID
WHERE C.STATE = 'Maharashtra';

SELECT A.ACC_ID, A.ACC_NO, A.CUST_ID, A.CUST_NAME 
FROM ACCOUNT A
JOIN CUSTOMER C ON A.CUST_ID = C.CUST_ID
WHERE C.STATE = 'Karnataka';

SELECT I.INVOICE_ID, I.ACC_NO, I.TARIFF_ID, I.READING_DATE, I.METER_ID 
FROM INVOICE I
LEFT JOIN ACCOUNT A ON I.ACC_NO = A.ACC_NO
LEFT JOIN CUSTOMER C ON A.CUST_ID = C.CUST_ID
WHERE C.STATE = 'Gujarat';

SELECT E.EBOARD_ID, E.EBOARD_NAME, COUNT(I.INVOICE_ID) AS TOTAL_INVOICES 
FROM ELEC_BOARD E
LEFT JOIN INVOICE I ON E.EBOARD_ID = I.EBOARD_ID
GROUP BY E.EBOARD_ID, E.EBOARD_NAME;